version: '3.9'
 
services:
  web:
    container_name: odoo_16
    image: odoo:16.0
    depends_on:
      - db
    ports:
      - "8069:8069"
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./config_odoo:/etc/odoo
      - ./dev_addons:/mnt/extra-addons
      - ./log:/var/log/odoo

  db:
    container_name: postgres_16
    image: postgres:16.0
    ports:
      - 5432:5432/tcp
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo_db
      - POSTGRES_USER=odoo_db
      - PGDATA=/var/lib/postgres/data/pgdata
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5  
 
volumes:
  odoo-web-data:
  odoo-db-data: